FROM debian:bookworm

RUN apt update &&  apt install -y \
    openssl \
    nginx \
    vim

RUN mkdir -p /etc/nginx/ssl 

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/CN=fifrandr.42.fr/UID=fifrandr"

COPY ./conf/default /etc/nginx/sites-enabled/default
COPY ./conf/default /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]